# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ers_admin', '0003_auto_20170902_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_id',
            new_name='token',
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.IntegerField(default=0, help_text='\u7ec8\u7aef\u63a5\u5165\u72b6\u6001: 0: \u672a\u6fc0\u6d3b 1: \u6b63\u5e38'),
        ),
    ]
