# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ers_admin', '0004_auto_20170904_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
