# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ers_admin', '0005_auto_20170905_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(default='234sdfewrwer', max_length=200),
            preserve_default=False,
        ),
    ]
